@extends('layouts.app')

@section('content')
@php
    $esDomiciliario = $esDomiciliario ?? false;
    $esAdmin = $esAdmin ?? false;
@endphp
<div class="dashboard-page">
    @if($esDomiciliario)
        @if($sinDomiciliario ?? false)
            <section class="dashboard-empty"><span class="dashboard-empty-icon">⚠️</span><h1>Perfil pendiente</h1><p>Contacta al administrador para configurar tu perfil de domiciliario.</p></section>
        @else
            <header class="dashboard-hero">
                <div><span class="dashboard-kicker">Operación de entregas</span><h1>Hola, {{ $domiciliario->nombre }}</h1><p>{{ $domiciliario->vehiculoLabel() }} · {{ now()->format('d/m/Y H:i') }}</p></div>
                <div class="dashboard-hero-actions"><a href="{{ route('rutas.disponibles') }}" class="dashboard-button dashboard-button-primary">Ver disponibles <span>{{ $disponiblesCount }}</span></a><a href="{{ route('rutas.index') }}" class="dashboard-button dashboard-button-ghost">Mis rutas</a></div>
            </header>
            <section class="dashboard-kpis dashboard-kpis-five">
                <x-dashboard-kpi icon="◎" label="Disponibles" :value="$disponiblesCount" tone="gold" />
                <x-dashboard-kpi icon="↗" label="Aceptados" :value="$aceptadosCount" tone="info" />
                <x-dashboard-kpi icon="→" label="En camino" :value="$enCaminoCount" tone="warning" />
                <x-dashboard-kpi icon="✓" label="Entregas hoy" :value="$entregasHoy" tone="success" />
                <x-dashboard-kpi icon="$" label="Ganado hoy" :value="'$'.number_format($gananciaHoy, 0, ',', '.')" tone="gold" />
            </section>
            <section class="dashboard-grid dashboard-grid-two">
                <div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Rendimiento</span><h2>Ganancias de entregas</h2></div><span class="dashboard-live">Actualizado</span></div><div class="dashboard-chart-wrap"><canvas id="dashboard-trend-chart"></canvas></div></div>
                <div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Balance</span><h2>Resumen de ganancias</h2></div></div><div class="dashboard-balance-list"><div><span>Hoy</span><strong>${{ number_format($gananciaHoy, 0, ',', '.') }}</strong></div><div><span>Este mes · {{ $entregasMes }} entregas</span><strong>${{ number_format($gananciaMes, 0, ',', '.') }}</strong></div><div><span>Total histórico</span><strong>${{ number_format($gananciaTotal, 0, ',', '.') }}</strong></div><div><span>Domicilios externos</span><strong>{{ $externosRealizados }}</strong></div></div></div>
            </section>
            @if($rutaActiva)
                <section class="dashboard-panel dashboard-route"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Ruta activa</span><h2>{{ $rutaActiva->tipoLabel() }} #{{ $rutaActiva->id }}</h2></div><a href="{{ route('rutas.show', $rutaActiva) }}" class="dashboard-text-link">Continuar →</a></div><div class="dashboard-progress"><span style="width:{{ $rutaActiva->domicilios->count() ? round($rutaActiva->domicilios->where('estado','entregado')->count() / $rutaActiva->domicilios->count() * 100) : 0 }}%"></span></div><p class="dashboard-muted">{{ $rutaActiva->domicilios->where('estado','entregado')->count() }}/{{ $rutaActiva->domicilios->count() }} entregados</p></section>
            @endif
            <section class="dashboard-grid dashboard-grid-two"><div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Historial</span><h2>Últimas entregas</h2></div></div><div class="dashboard-activity-list">@forelse($historialEntregas as $entrega)<div><span class="dashboard-activity-icon">✓</span><div><strong>{{ $entrega->nombre_cliente }}</strong><small>{{ $entrega->direccion }} · {{ $entrega->fecha_entrega_real?->format('d/m/Y H:i') }}</small></div><b>${{ number_format($entrega->tarifa_monto, 0, ',', '.') }}</b></div>@empty<p class="dashboard-muted">Aún no hay entregas registradas.</p>@endforelse</div></div><div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Acciones</span><h2>Accesos rápidos</h2></div></div><div class="dashboard-quick-grid"><a href="{{ route('rutas.disponibles') }}">◎<span>Tomar domicilio</span></a><a href="{{ route('rutas.index') }}">▤<span>Mis rutas</span></a><a href="{{ route('profile.edit') }}">◌<span>Mi perfil</span></a><form action="{{ route('logout') }}" method="POST">@csrf<button type="submit">↪<span>Cerrar sesión</span></button></form></div></div></section>
        @endif
    @elseif(!$esAdmin && ($sinVendedor ?? false))
        <section class="dashboard-empty"><span class="dashboard-empty-icon">⚠️</span><h1>Cuenta pendiente</h1><p>Tu cuenta aún no está vinculada a un vendedor.</p><a href="{{ route('ventas.create') }}" class="dashboard-button dashboard-button-primary">Registrar venta</a></section>
    @elseif($esAdmin)
        @php $hoyStr = now()->toDateString(); $mesStr = now()->startOfMonth()->toDateString(); @endphp
        <header class="dashboard-hero"><div><span class="dashboard-kicker">Centro de operaciones</span><h1>Panel de control</h1><p>Hola, {{ auth()->user()->name }} · {{ now()->format('d/m/Y H:i') }}</p></div><div class="dashboard-hero-actions"><a href="{{ route('ventas.create') }}" class="dashboard-button dashboard-button-primary">+ Nueva venta</a><a href="{{ route('productos.create') }}" class="dashboard-button dashboard-button-ghost">Nuevo producto</a><a href="{{ route('clientes.create') }}" class="dashboard-button dashboard-button-ghost">Nuevo cliente</a></div></header>
        <section class="dashboard-kpis dashboard-kpis-six">
            <x-dashboard-kpi icon="₿" label="Ventas brutas hoy" :value="'$'.number_format($ventasBrutasHoy, 0, ',', '.')" tone="gold" />
            <x-dashboard-kpi icon="◷" label="Ventas brutas mes" :value="'$'.number_format($ventasBrutasMes, 0, ',', '.')" tone="info" />
            <x-dashboard-kpi icon="✓" label="Ventas pagadas mes" :value="'$'.number_format($ingresosMes, 0, ',', '.')" tone="success" />
            <x-dashboard-kpi icon="!" label="Pendiente por cobrar" :value="'$'.number_format($pendienteCobro, 0, ',', '.')" tone="warning" />
            <x-dashboard-kpi icon="$" label="Comisiones pendientes" :value="'$'.number_format($comisionesTotales, 0, ',', '.')" tone="danger" />
            <x-dashboard-kpi icon="↗" label="Pedidos activos" :value="$pedidosPendientes" tone="info" />
        </section>
        <section class="dashboard-grid dashboard-grid-four"><div class="dashboard-panel dashboard-panel-span-two"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Tendencia</span><h2>Ventas y domicilios · últimos 14 días</h2></div></div><div class="dashboard-chart-wrap"><canvas id="dashboard-trend-chart"></canvas></div></div><div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Logística</span><h2>Domicilios</h2></div></div><div class="dashboard-balance-list"><div><span>Cobrado en domicilios</span><strong>${{ number_format($totalCobradoDomiciliosMes, 0, ',', '.') }}</strong></div><div><span>Generado para domiciliarios</span><strong>${{ number_format($generadoDomiciliariosMes, 0, ',', '.') }}</strong></div><div><span>Ganancia neta estimada</span><strong>${{ number_format($gananciaNetaDomiciliosMes, 0, ',', '.') }}</strong></div><div><span>Externos entregados</span><strong>{{ $domiciliosExternosMes }}</strong></div></div></div><div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Estado ahora</span><h2>Operación</h2></div></div><div class="dashboard-balance-list"><div><span>Pedidos activos</span><strong>{{ $pedidosPendientes }}</strong></div><div><span>Domicilios pendientes</span><strong>{{ $domiciliosPendientes }}</strong></div><div><span>En camino</span><strong>{{ $domiciliosEnCamino }}</strong></div><div><span>Entregados hoy</span><strong>{{ $domiciliosEntregadosHoy }}</strong></div><div><span>Productos agotados</span><strong>{{ $productosAgotados }}</strong></div></div></div></section>
        @if($comisionesTotales > 0 || $domiciliosPendientes > 0 || $productosAgotados > 0)<section class="dashboard-alerts">@if($comisionesTotales > 0)<a href="{{ route('vendedores.index') }}">Comisiones pendientes <strong>${{ number_format($comisionesTotales, 0, ',', '.') }}</strong><span>Revisar →</span></a>@endif @if($domiciliosPendientes > 0)<a href="{{ route('domicilios.index') }}">Domicilios sin asignar <strong>{{ $domiciliosPendientes }}</strong><span>Ver →</span></a>@endif @if($productosAgotados > 0)<a href="{{ route('productos.index', ['stock_bajo' => 1]) }}">Productos agotados <strong>{{ $productosAgotados }}</strong><span>Ver →</span></a>@endif</section>@endif
        <section class="dashboard-grid dashboard-grid-two"><div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Actividad reciente</span><h2>Últimas ventas</h2></div><a href="{{ route('ventas.index') }}" class="dashboard-text-link">Ver todas →</a></div><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>#</th><th>Cliente</th><th>Vendedor</th><th>Total</th><th>Estado</th></tr></thead><tbody>@forelse($ventasRecientes as $venta)<tr><td>{{ $venta->id }}</td><td>{{ $venta->cliente->nombre ?? '—' }}</td><td>{{ $venta->vendedor->nombre ?? '—' }}</td><td class="dashboard-money">${{ number_format($venta->total, 0, ',', '.') }}</td><td><span class="dashboard-status dashboard-status-{{ $venta->estado }}">{{ $venta->estado_label }}</span></td></tr>@empty<tr><td colspan="5">Sin ventas aún.</td></tr>@endforelse</tbody></table></div></div><div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Inventario</span><h2>Top productos</h2></div><a href="{{ route('productos.index') }}" class="dashboard-text-link">Catálogo →</a></div><div class="dashboard-ranking">@forelse($topProductos as $i => $producto)<div><span>{{ str_pad($i + 1, 2, '0', STR_PAD_LEFT) }}</span><strong>{{ $producto->nombre_producto }}</strong><small>{{ $producto->total_vendido }} uds · ${{ number_format($producto->total_ingresos, 0, ',', '.') }}</small></div>@empty<p class="dashboard-muted">Sin datos todavía.</p>@endforelse</div></div></section>
    @else
        @php $domiciliario = auth()->user()->domiciliario; @endphp
        <header class="dashboard-hero"><div><span class="dashboard-kicker">Tu operación</span><h1>Hola, {{ $vendedor->nombre }}</h1><p>Vendedor{{ $domiciliario ? ' · también domiciliario' : '' }} · {{ now()->format('d/m/Y H:i') }}</p></div><div class="dashboard-hero-actions"><a href="{{ route('ventas.create') }}" class="dashboard-button dashboard-button-primary">+ Nueva venta</a><a href="{{ route('vendedores.show', $vendedor) }}" class="dashboard-button dashboard-button-ghost">Mis ganancias</a>@if($domiciliario)<a href="{{ route('rutas.disponibles') }}" class="dashboard-button dashboard-button-ghost">Tomar domicilio</a>@endif</div></header>
        <section class="dashboard-kpis dashboard-kpis-five"><x-dashboard-kpi icon="₿" label="Ventas hoy" :value="$ventasHoy" tone="gold" /> <x-dashboard-kpi icon="◷" label="Ventas este mes" :value="$ventasMes" tone="info" /> <x-dashboard-kpi icon="$" label="Comisión generada" :value="'$'.number_format($comisionTotal, 0, ',', '.')" tone="success" /> <x-dashboard-kpi icon="!" label="Comisión pendiente" :value="'$'.number_format($comisionPendiente, 0, ',', '.')" tone="warning" /> @if($domiciliario) <x-dashboard-kpi icon="🛵" label="Ganancia domicilios mes" :value="'$'.number_format($gananciaDomiciliosMes, 0, ',', '.')" tone="gold" /> @endif</section>
        <section class="dashboard-grid dashboard-grid-two"><div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Rendimiento</span><h2>Actividad de los últimos 14 días</h2></div></div><div class="dashboard-chart-wrap"><canvas id="dashboard-trend-chart"></canvas></div></div><div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Balance</span><h2>Ganancia combinada</h2></div></div><div class="dashboard-balance-list"><div><span>Comisiones de ventas</span><strong>${{ number_format($comisionTotal, 0, ',', '.') }}</strong></div><div><span>Comisión ya pagada</span><strong>${{ number_format($comisionCobrada, 0, ',', '.') }}</strong></div><div><span>Domicilios este mes</span><strong>${{ number_format($gananciaDomiciliosMes ?? 0, 0, ',', '.') }}</strong></div><div><span>Total histórico domicilios</span><strong>${{ number_format($gananciaDomiciliosTotal ?? 0, 0, ',', '.') }}</strong></div></div></div></section>
        <section class="dashboard-grid dashboard-grid-two"><div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Actividad reciente</span><h2>Mis ventas</h2></div><a href="{{ route('ventas.index') }}" class="dashboard-text-link">Ver todas →</a></div><div class="dashboard-table-wrap"><table class="dashboard-table"><thead><tr><th>#</th><th>Cliente</th><th>Total</th><th>Estado</th></tr></thead><tbody>@forelse($ventasRecientes as $venta)<tr><td>{{ $venta->id }}</td><td>{{ $venta->cliente->nombre ?? '—' }}</td><td class="dashboard-money">${{ number_format($venta->total, 0, ',', '.') }}</td><td><span class="dashboard-status dashboard-status-{{ $venta->estado }}">{{ $venta->estado_label }}</span></td></tr>@empty<tr><td colspan="4">Sin ventas aún.</td></tr>@endforelse</tbody></table></div></div><div class="dashboard-panel"><div class="dashboard-panel-heading"><div><span class="dashboard-kicker">Productos</span><h2>Más vendidos</h2></div></div><div class="dashboard-ranking">@forelse($topProductos as $i => $producto)<div><span>{{ str_pad($i + 1, 2, '0', STR_PAD_LEFT) }}</span><strong>{{ $producto->nombre_producto }}</strong><small>{{ $producto->total_vendido }} uds · ${{ number_format($producto->total_ingresos, 0, ',', '.') }}</small></div>@empty<p class="dashboard-muted">Sin datos todavía.</p>@endforelse</div></div></section>
    @endif
</div>
@if(isset($chartLabels))
<script>
window.dashboardChartData = @json(['labels' => $chartLabels, 'ventas' => $chartVentas, 'domicilios' => $chartDomicilios]);
document.addEventListener('DOMContentLoaded', function () {
    const canvas = document.getElementById('dashboard-trend-chart');
    if (!canvas || !window.Chart || !window.dashboardChartData) return;
    const styles = getComputedStyle(document.documentElement);
    const gold = styles.getPropertyValue('--pg-gold').trim();
    const info = styles.getPropertyValue('--pg-info').trim();
    const muted = styles.getPropertyValue('--pg-muted').trim();
    const border = styles.getPropertyValue('--pg-border').trim();
    new Chart(canvas, { type: 'line', data: { labels: window.dashboardChartData.labels, datasets: [
        { label: 'Ventas', data: window.dashboardChartData.ventas, borderColor: gold, backgroundColor: 'rgba(205,168,106,.12)', fill: true, tension: .35, pointRadius: 3 },
        { label: 'Domicilios', data: window.dashboardChartData.domicilios, borderColor: info, backgroundColor: 'transparent', tension: .35, pointRadius: 3 }
    ]}, options: { responsive: true, maintainAspectRatio: false, plugins: { legend: { labels: { color: muted, usePointStyle: true } } }, scales: { x: { grid: { color: border }, ticks: { color: muted } }, y: { grid: { color: border }, ticks: { color: muted, callback: value => '$' + Number(value).toLocaleString('es-CO') } } } } });
});
</script>
@endif
@endsection
